---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
    service: ${REPO}
    dir_name: null
  triggers:
  - type: commit
  properties:
  - name: CHART_NAME
    value: ${CHART_NAME}
    type: text
  - name: mda_url
    value: https://s3.amazonaws.com/mendix-test-bucket/default.mda
    type: text
  - name: mendix_template
    value: 94a763f5-864c-4e43-b992-056694479974
    type: text
  jobs:
  - name: Build
    type: builder
    build_type: cr
    artifact_dir: ''
    script: |-
          #!/bin/bash

          echo "source the container_build script to run in current shell"
          wget -O mendix.mda ${mda_url}
          echo "mda ${mda_url}"
          SCRIPTS_DIR=.bluemix/scripts # SCRIPTS_DIR is used in container_build.sh
          source ${SCRIPTS_DIR}/container_build.sh

          if  [[ -f container_build.sh ]]; then
            chmod +x post_build.sh;
            echo "executing the container_build script";
            sh container_build.sh;
          else
            echo "the container_build script does not exist";
          fi
    namespace: ${REGISTRY_NAMESPACE}
    image_name: ${CHART_NAME}
    target:
      region_id: ${REGION_ID}
      api_key: ${API_KEY}
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: buildProperties
    value: build.properties
    type: file
  - name: RELEASE_NAME
    value: ${CHART_NAME}
    type: text
  - name: CLUSTER_NAMESPACE
    value: ${CLUSTER_NAMESPACE}
    type: text
  - name: IMAGE_REGISTRY_TOKEN
    value: ${IMAGE_REGISTRY_TOKEN}
    type: text
  jobs:
  - name: Deploy
    type: deployer
    deploy_permission: DEV_IN_SPACE
    deploy_type: kubernetes
    target:
      region_id: ${REGION_ID}
      api_key: ${API_KEY}
      kubernetes_cluster: ${KUBE_CLUSTER_NAME}
    script: |-
      #!/bin/bash
      echo "source the kube_deploy script to run in current shell"
      source .bluemix/scripts/kube_deploy.sh
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: http://lms-api/v1/messaging/webhook/publish
